# Generated by Django 5.2.1 on 2025-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('redirect_url', models.URLField(verbose_name='Yönlendirilecek URL')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR Kod Görseli')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='QR Kod Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'QR Kodu',
                'verbose_name_plural': 'QR Kodları',
            },
        ),
    ]
