# Generated by Django 5.2.1 on 2025-05-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_qrcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silinmiş mi'),
        ),
    ]
